language: java
jdk:
  - openjdk15

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$Home/.m2/repository'
    - '$Home/.gradle'


script: "./gradlew clean build"

before_deploy:
  - zip -r SpringBoot-AWS *
  - mkdir -p deploy
  - mv SpringBoot-AWS.zip deploy/SpringBoot-AWS.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY  #Travis repo setting
    secret_access_key: $AWS_SECRET_KEY
    bucket: springaws-build #S3 버킷 이름.
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-untill-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springaws-build
    key: SpringBoot-AWS.zip
    bundle_type: zip
    application: spring-aws-webservice #CodeDeploy 애플리케이션
    deployment_group: spring-aws-webservice-group #CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait_until-deployed: true

# CI 실행 완료 시 메일로 알람.
notifications:
  email:
    recipients:
      - kimtaejun9705@gmail.com

